services:
  - type: web
    name: gdrive-sync-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 -m bot
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: APP_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: MONGO_URI
        sync: false
      - key: SUDO_USERS
        sync: false
      - key: G_DRIVE_SERVICE_ACCOUNT_JSON
        sync: false
      - key: G_DRIVE_CLIENT_ID
        sync: false
      - key: G_DRIVE_CLIENT_SECRET
        sync: false
      - key: REDIRECT_URI
        sync: false
      - key: MAX_WORKERS
        value: "3"
      - key: POLL_INTERVAL
        value: "45"
      - key: DOWNLOAD_DIRECTORY
        value: "./downloads/"
      - key: FAILED_DIRECTORY
        value: "./failed/"
      - key: PORT
        value: "8080"
